pyOpenSci/software-peer-review

- content/appendices/templates.md
This is a suggestion to avoid confusion in what belongs in the readme of all packages.
> Add specific readme requirements to review template

- content/appendices/templates.md
This is a stab at fixing #33, which references a `DESCRIPTION` file (an R thing). Instead, the metadata on urls, authors, etc. might go in a `setup.py` file. I kept the language somewhat vague to accommodate exceptional circumstances, but I think we should at least ask for the URL and author info somewhere.
> Remove reference to DESCRIPTION

- authoring/tools-for-developers.md
Add tools for development to menu and fix link inside the note.
I just saw that the other filenames use underscore instead of dash. 
I created the file using dash, should I change to underscore? In general dash is more used or recommend (for example https://support.google.com/webmasters/answer/76329?hl=en), but I can change to underscore with no problem.
note: menu was already added! thanks @lwasser
> authoring/tools-for-developers: Fix link inside a note 

- .circleci/config.yml
- .github/workflows/book.yml
- _config.yml
- _toc.yml
- authoring/index.md
- open-source-software-peer-review/intro.md
- open-source-software-peer-review/policies-and-guidelines.md
- open-source-software-submissions/editor-in-chief-guide.md
- open-source-software-submissions/intro.md
- requirements.txt
This makes some minor formatting and structure updates to make the docs a bit easier to read in pure-text (e.g. splitting really long lines into multiple shorter lines). It re-orders a couple of pages to (I think) more naturally flow (e.g. "overview" should go first). It also renames the titles of a few pages that felt awkwardly long.
> minor document updates and adding repository buttons

- README.md
- appendices/templates.md
- authoring/collaboration.md
- intro.md
- open-source-software-submissions/editors-guide.md
- open-source-software-submissions/reviewer-guide.md
There appears to be a number of outdated URLs in the contributing guide. This PR should fix them.
> Fix urls in various places throughout the contributing guide

- authoring/overview.md
GitHub Actions with its ability to support all 3 major OS has become the de facto CI choice in the past year.
> Add GitHub Actions and CircleCI for CI options

- open-source-software-submissions/editors-guide.md
Noticed this reference to a bot while I was finishing up a review, and a comment after it that I'm guessing was @lwasser making a note to self when drafting the guide 
> to update the reminder bot. <WHAT IS THIS BOT?!>
@lwasser guessing you don't mind if I remove it
> remove reference to a bot in editors-guide.md

- README.md
- _toc.yml
- open-source-software-submissions/intro.md
This PR just unnests sections so they are more visible in the guide. i haven't edited any content. 
This stems from feedback from @kcranston and @xmnlab  
the new TOC will look like this:
> ORG: unnest peer review subsections

- _toc.yml
- open-source-software-peer-review/aims-and-scope.md
- open-source-software-peer-review/intro.md
- open-source-software-peer-review/policies-and-guidelines.md
- open-source-software-peer-review/policies-guidelines.md
- open-source-software-submissions/author-guide.md
This PR adds:
* More extensive policies around peer review
* More background on peer review and why it's important
* some language around maintainers and expected communication
This PR has grown a bit. 
I updated the authors guide to include a section on maintenance. i think it's important that these are not one-off submissions ... that long term maintenance is considered. and the submitting author needs to be around to communicate with us about the package... so it's different from a paper review in that sense.. because software is a living tool not a one off script. 
we will need to finesse and better define this language as we move forward but this is a start. The policies are also heavily updated... but some sections still need to be more fleshed out... 
While I think more work needs …
> CONTENT: Update policies for peer review

- .github/workflows/artifact_redirect.yml
Only run the artifact redirector when the status that triggers it is a circleCI build
> Quick fix: Filter artifact redirect workflow

- .github/workflows/artifact_redirect.yml
- .github/workflows/book.yml
- README.md
- Added GitHub Actions badge
- Documented build redundancy
- Added explanation of how to view  preview via CircleCI, GitHub Actions, and the artifact redirector workflow. 
@lwasser let me know what you think! Should we add images to the README to help explain how to view the preview? Or more or less detail?
> Document website build

- README.md
Need to fix links in the README after renaming repo to peer-review-guide
> Fix 'contributing-guide' -> 'peer-review-guide' in README links

- README.md
Just a small fix in the badge - it was directing to the wrong build name
> FIX: readme actions badge

- .zenodo.json
This adds all of the previous contributors that were removed when i moved to the .zenodo.json file.
We should create a new release once the open PR is merged next week to recognize everyone. ideally we can also add all of these folks to our contributor section in the readme too.
> Add: all contributors to zenodo file

- appendices/review-template.md
- how-to/reviewer-guide.md
This pull request updates documentation and template for reviewers.
Closes #198.
Thanks for considering it.
> Update documentation and template for reviewers about tests

- how-to/editor-in-chief-guide.md
- how-to/onboarding-guide.md
- Add info on giving new editors GitHub permissions in onboarding-guide.md.
- Add links to onboarding guide from editor-in-chief guide.
- Also fix a link to review-mentorship in editor-in-chief.md
> Add info on GitHub permissions, fix #195

- index.md
Resolves #209 
We decided to get rid of the section since it's essentially redundant. 
cc @chiinita
> Fix: Remove redundant "Review guide" section

- partners/pangeo.md
This pull request fixes the failing [HTML-proofer check](https://github.com/pyOpenSci/software-peer-review/actions/runs/4994719748/jobs/8945670685) currently happening on main.
Thanks for considering it. :)
> Fix HTML-Proofer failure for 2i2c documentation

- appendices/editor-in-chief-checks.md
It feels like this isn't the right place to be recommending specific implementation details for these checks, and this reduces the amount of text here a bit to make it easier to follow
> Remove implementation suggestions from checks

- how-to/author-guide.md
Minor edits performed to close out #246
> Minor edits to the Author guide

- appendices/package-approval-template.md
A small PR that fixes language for the final step of review. We now have an automated workflow that adds people to the website and adds the package as well. it's better to use the automated workflow for consistency but also it's less work for wrapping up a review!
> Fix: remove language around adding package and contribs to website

- appendices/package-approval-template.md
- conf.py
- how-to/editors-guide.md
This PR does a few things. 
1. it fixes a minor footer pydata sphinx theme deprecation
2. it adds some language about the types of reviewers we ideally want for each package
3. it updates the checklist at the end to include inviting folks to slack. 
i'd love a review from 1-2 members our of @pyOpenSci/editorial-board if that is possible!! many thanks y'all!!
> Fix: update editor steps to include reviewer info & update checklist

- conf.py
- how-to/author-guide.md
- how-to/editors-guide.md
- index.md
this pr adds boxes at the top of the author guide to other core peer review resources. 
NOTE: one issue now is some of these are list below. AND looking at the page i think the steps to initiate a review are not clear. open to additional feedback on making this page a more more clear for people thinking about submitting to us. 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206075195584329
> Fix: add favicon and add blocks to author guide

- how-to/reviewer-guide.md
I recommend always using long-form command-line arguments (where available) in documentation. It helps make documentation more "documentary"
> Use long form command-line argument for "self-documentation"

- our-process/policies.md
closes #254 
this PR addresses the topic discussed in #254 it adds language around what we track and how we flag packages that may be en route to becoming orphans / unmaintained. 
it is now open for formal review from the community. 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205816362403674
- https://app.asana.com/0/0/1206105000277660
> Fix: update archive package text

- .circleci/config.yml
- .github/workflows/artifact_redirect.yml
This should fix the CI action that creates a easy redirect to the built guidebook packages
it adds
* the needed circle ci token (which is at the organization level now and scoped for just the repos it needs access to
* updated the build to build-book (no underscore)
* setups up concurrency to avoid duplicate builds
> Fix: fix redirect action for previous

- requirements.txt
The pydata sphinx theme fix has not been implemented yet. as such this pins the version so our left side nav works again!
> Fix: pin pydata sphinx to get left side bar nav back

- .github/workflows/build-book.yml
This PR updates actions to the their latest version to remove the deprecation warnings currently issued after each workflow run.
> Fix: Update actions to the most current versions

- how-to/editor-in-chief-guide.md
Based on internal conversations, I updated the instance of `1-editor-checks` to ` 0/pre-review-checks `, and added `1/editor-assigned` to step four.
I also added two missing octothorpes to references to Slack channels.
> UPDATE: align EIC Guide tasks with GitHub labels

- about/package-scope.md
- index.md
This pr updates our scope statement found in the peer review guide to specifically address analytics related packages. It is now open for community review! 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206952129256524
> Fix: update scope criteria for analytics packages

- CONTRIBUTING.md
- code-of-conduct.md
- conf.py
- how-to/editors-guide.md
- how-to/reviewer-guide.md
- our-process/how-review-works.md
- partners/scientific-communities.md
This updates all links to pyos/governance. --> pyopensci/handbook
> Fix: update governance --> handbook

- conf.py
- how-to/author-guide.md
- how-to/finding-reviewers.md
- how-to/onboarding-guide.md
i added commits on top of #290 but something is super funky with those commits! it should be ok however once we merge. 
what is actually missing from this page now is reviewer onboarding!! so i'll open this in draft.
> ENH: updates to editor & reviewer onboarding pages

- about/intro.md
- appendices/package-approval-template.md
- how-to/author-guide.md
- how-to/editors-guide.md
- index.md
Implements: https://github.com/pyOpenSci/software-peer-review/issues/293
Depends on: https://github.com/pyOpenSci/pyopensci.github.io/pull/428
Pretty simple! Basically I think link shorteners are bad, there's no reason to effectively embed a tracking pixel in every reviewed repo, and in this case it would be nice to give a nice canonical location to these badges that is sure to exist for as long as we do as an organization :).
> Switch url to pyopensci from tinyurl

- README.md
- our-process/policies.md
- partners/pangeo.md
This pr updates our on-hold policy to better align with rOpenSci. We have support from 5 editors in slack and did discuss this there! After this is merged, i will close a few issues that have been open for over a year!
> feat(policy): add policy around on hold and stale reviews

- about/package-scope.md
- how-to/finding-reviewers.md
**Fixes**
- Adjusts the language to reflect the editor's steps while finding a mentor for a new reviewer.
- Remove `label` from the URL, and adjust wording to fix htmlproofer error.
resolves #313
> docs: adjust language for peer review mentorship

- appendices/editor-in-chief-checks.md
- appendices/review-template.md
- how-to/editor-in-chief-guide.md
closes #259 , #289 
This adds a note about how maintainers can add a .github repo to their org to maintain standard defaults for LICENSE, COC and more using SunPy as an example!
> enh: add .github repo with defaults to eic checks

- our-process/policies.md
Add revised requirements for acceptance by pyOS if a JOSS publication already exists.
> enh(JOSS policy): Revise JOSS discussion
