pyOpenSci/software-peer-review

- content/appendices/templates.md
- content/intro.md
- content/packaging/packaging_guide.md
- content/peer_review/author_guide.md
- content/peer_review/editor_guide.md
- content/peer_review/peer_review_proc.md
- content/peer_review/reviewer_guide.md
Also added conflict of interest section
> Updated links and removed some ropensci stuff

- content/appendices/templates.md
- content/peer_review/editor_guide.md
as a part of setting up our FIRST REVIEW i am editing the dev_guide contents.
@npch @choldgraf @jlpalomino if you can do the same as you go through your review it would be wonderful.
> Editor Review content edits

- .circleci/config.yml
I *think* this may fix the build
> adding all files in the build

- content/packaging/packaging_guide.md
Also checking to be sure that CI is building book correctly #16
> Add clear requirement for installation instructions in README

- content/intro.md
> minor typo

- README.md
- _config.yml
- _toc.yml
- appendices/glossary.md
- appendices/templates.md
- authoring/collaboration.md
- authoring/index.md
- authoring/overview.md
- authoring/packaging_guide.md
- authoring/testing.md
- intro.md
- process/guidelines.md
- submissions/author_guide.md
- submissions/editor_guide.md
- submissions/reviewer_guide.md
Updating a bunch of documentation and cleaning up some old PRs. It doesn't generally change much of the content, but moves a couple things around so they're easier to discover etc.
closes https://github.com/pyOpenSci/dev_guide/issues/52
closes https://github.com/pyOpenSci/dev_guide/issues/8
closes https://github.com/pyOpenSci/dev_guide/issues/13
closes https://github.com/pyOpenSci/dev_guide/pull/42
I'll plan to merge this in if the tests are happy so we can keep iterating!
> Docs update

- authoring/git-pre-commit-hook.md
- authoring/tools-for-developers.md
This PR adds information about git pre-commit hook.
> Add doc about git pre commit hook

- submissions/reviewer_guide.md
this addresses #61 
I also think we should update the blog posts in the FUTURE if a review wants to share their experience reviewing for us!!
> small updates POS reviews rather than RO

- authoring/collaboration.md
> Fix a collaboration label and Improve a collaboration note

- authoring/overview.md
Not sure where would be the best place to add this information. 
this PR is related to https://github.com/pyOpenSci/cookiecutter-pyopensci/issues/17
any suggestion or recommendation here would be very welcome :)
> Add suggestion about python versions support

- _toc.yml
- appendices/templates.md
it needed some love :) pyrolite was approved today -- YAY!!
> updates to the editor template

- .circleci/config.yml
- appendices/templates.md
- open-source-software-submissions/editors-guide.md
- requirements.txt
closes #80 
Sorry that this took so long @NickleDave  will look at the related issue next.
this also addresses part of #81 by making the review  request email template "code" so it can be easily copied.  81 is NOT fully addressed here however.
> fix coi link

- _static/pyos.css
- open-source-software-submissions/editors-guide.md
- open-source-software-submissions/intro.md
will close #75  (joss instructions)
as i work through this cleaning up broken links and streamlining content
> cleanup of guide part ii

- open-source-software-submissions/editors-guide.md
A few more minor edits after chatting with arfon #75
> A few more minor fixes

- open-source-software-submissions/author-guide.md
> Adding links in author-guide.md

- .github/workflows/book.yml
- README.md
- _config.yml
- _static/pyos.css
- _toc.yml
- intro.md
- open-source-software-peer-review/aims-and-scope.md
- open-source-software-peer-review/intro.md
- open-source-software-peer-review/policies-and-guidelines.md
- open-source-software-submissions/author-guide.md
- open-source-software-submissions/intro.md
- requirements.txt
- scope.md
This is the beginning of trying to make the editorial process overall more clear and defining processes.
I mostly targeted the author guide here and cleaned up the TOC. it builds on top of #106 which is a simple unnesting of those sections. 
THIS PR does the following:
✅ Adds a new landing page tot he contributing guide directing various users to different parts of the guide. we can adjust this as we build more content to make it super clear
✅ Updates content in the reviewers, editor and most broadly author guide to be more clear. I spent the most time on the author guide
✅ it also updates some information and unnests most of the guidebook to make the navigation simpler.
✅  Adds a zenodo badge to the readme and book landing page and I created a release before this PR goes through just so …
> Author guide cleanup

- _toc.yml
- open-source-software-submissions/onboarding-guide.md
ok phew! here is a guide for onboarding new editors.
I think all new editors should serve as a guest at first for their first review. we can mentor them as needed.
I am hoping we can merge this today but if anyone does want to review feel free. I just wanted to get this pulled together so we can begin to create an editorial team / have processes in place to do so. 
next step is a call for editors and i'm almost done with a survey form for new editors to apply.
> CONTENT: onboarding of editors

- README.md
- _config.yml
- intro.md
- open-source-software-submissions/intro.md
This just brings a few updates from the EIC #112 PR over that need to be fixed sooner rather than later. And it adds a version badge which i think is important.
> CONTENT: updated badges for versioning and intro page cleanup

- README.md
- open-source-software-submissions/editors-guide.md
This PR:
* Updates the editor guide with responsibilities and time commitment - questions i've been getting a lot when talking with folks about being on the editorial board. 
Nevermind. i'll deal with CI in a separate build. html proofer isn't here.
> CONTENT: editor guide update w responsibilities

- .github/workflows/build-book.yml
had to write an issue to potentially figure out why this stopped working. had nothing to do with regex IF this fixes things.
closes #133
> INFRA: fix build to check correct dir

- conf.py
- requirements.txt
This just adds the sitemap and opengraph packages to our build to support google SEO things.
> ADD: add sitemap to build for google search support

- .zenodo.json
hey @arianesasso @NickleDave @batalex can you please have a look at this zenodo file and make sure your info is correct / add orcid id's  and organizations if you have them and want to?
> Add zenodo file for release publication

- conf.py
- how-to/author-guide.md
- index.md
i am trying to address our 2 most common questions which are:
how do we relate to JOSS / partnerships and 
What is our scope for review
so i added both to the landing page grid! also added a mastodon link to the header! yay pydata_sphinx_theme for the win i think . it has everything that we need. and we can grow the content over time as our programs grow.
> Add partners and scope to grid

- appendices/editor-initial-response-template.md
Also changed pyOpenSci capitalization for consistency.
> fix: Fix broken links in editor initial response

- .all-contributorsrc
> Fix: all contributors json

- README.md
> Fix: badge link

- about/package-scope.md
as per https://github.com/pyOpenSci/software-peer-review/pull/162#discussion_r1113749119
> Tweak wording of admonition in package-scope.md

- _static/matomo.js
- conf.py
Many thanks to @choldgraf for providing instructions here 
https://github.com/pydata/pydata-sphinx-theme/pull/1227/files
> Fix: Remove GA and add Matomo analytics

- how-to/author-guide.md
Closes gh-150
(Didn't test this locally 🤞🏽)
> Fix scope link

- about/intro.md
Closes Issue number #230 Made several typo corrections throughout the intro - including missing punctuation.
> Updating the introduction page in the software review guide to make some typo changes

- about/benefits.md
Aiming to close out #238 with the minor text revisions made to the "Benefits' page within the Software Review Process.
> Minor text revisions and corrections to the Benefits page

- about/package-scope.md
> Minor changes to the Package scope page

- CONTRIBUTING.md
Spelling error fixed on the Contributing page to close out #244
> Fixed spelling error on the Contributing page

- our-process/review-timeline.md
> A few minor edits on the Software review process page

- .github/workflows/build-book.yml
- how-to/review-triage-team.md
- partners/pangeo.md
This pr just addresses the broken links we see in #253
> Fix: a few broken urls

- how-to/editors-guide.md
This PR aims to remove an unnecessary word that is used twice.
> Small fix for the text in editors-guide.md

- README.md
This should also force a rebuild so the navigation returns!
> Fix: readme logo

- how-to/reviewer-guide.md
It appears the reviewer guide was missing a `[` ;).
> Fix broken link in reviewer guide.

- how-to/editor-in-chief-guide.md
- our-process/policies.md
For https://github.com/pyOpenSci/software-peer-review/issues/306
Provide editor guidelines on archiving inactive projects per the process developed in https://github.com/pyOpenSci/pyosMeta/pull/242
> Add guidelines on archiving inactive packages
